### PR TITLE
#5 use latest package and strong typing for map

### PR DESCRIPTION
**Pull request by khmak3**

### CODE REVIEW

**Comment by khmak3** [comment]
Any issue for the pull request?

**Comment by Patte1808** [comment]
Hey sorry that that happend and thanks for your PR :)
I'm not maintaining this repository as I'm not actively using Flutter at this moment and I've missed the notification from Github, sorry about that. :/

It looks good, but I don't understand why your pubspec.yaml and pubspec.lock differs. Do you know the reason for that?

**Comment by khmak3** [comment]
For both http and html the pubspec.lock still fill for pubspec.yaml. Since the  lock still falling to the range in yaml
Lock file
http = 0.12.0.+2
html = 0.14.0+2
yaml
 http: ">=0.11.3+17 <= 0.12.0+2"
 html: ">=0.13.3+3 <= 0.14.0+2"

**Comment by Patte1808** [comment]
Ah I see, makes sense to me. I was confused about the `pedantic` dependency, but missed that it was coming as a transitive dependency.

Sorry that it took so long, was quite busy in RL and thanks for your PR :) 

I will try to upload it to pubspec this week

**Pull request merged**
